apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development-test
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: development
  labels:
    app: jishnujoshy/pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jishnujoshy/pythonapp
  template:
    metadata:
      labels:
        app: jishnujoshy/pythonapp 
    spec:
      containers:
      - name: nodeserver
        image: jishnujoshy/pythonapp:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: development
spec:
  selector:
    app: jishnujoshy/pythonapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 
