apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development-test
    
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: development
data:
  .dockerconfigjson: eyJhdXRocyI6eyJweXRob25hcHAiOnsidXNlcm5hbWUiOiJqaXNobnVqb3NoeSIsInBhc3N3b3JkIjoic2hhaXJzb24yIiwiZW1haWwiOiJqaXNobnVqb3NoeTY5OUBnbWFpb2wuY29tIiwiYXV0aCI6ImFtbHphRzUxYW05emFIazZjMmhoYVhKemIyNHkifX19
type: kubernetes.io/dockerconfigjson    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
  namespace: development
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp 
    spec:
      containers:
      - name: pythonappserver
        image: jishnujoshy/pythonapp:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
  namespace: development
spec:
  selector:
    app: pythonapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 
